# -*- coding: utf-8 -*-
"""project PM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wa8dm3UDAdgodFuh4ldR9pQAcIMaQh_1
"""

!pip install opencv-python scikit-image joblib

import os
import cv2
import joblib
import numpy as np

from tqdm import tqdm

from skimage.feature import hog

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.model_selection import train_test_split

dataset_path = "/content/drive/MyDrive/dataset pm"

from google.colab import drive
drive.mount('/content/drive')

import os

dataset_path = "/content/drive/MyDrive/dataset pm"

print(os.listdir(dataset_path))

train_path = os.path.join(dataset_path, "train")
val_path = os.path.join(dataset_path, "val")
test_path = os.path.join(dataset_path, "test")


classes = os.listdir(train_path)

print("TRAIN DATA")
for cls in classes:
    folder = os.path.join(train_path, cls)
    count = len(os.listdir(folder))
    print(f"{cls}: {count} gambar")
print("TEST DATA")
for cls in classes:
    folder = os.path.join(test_path, cls)
    count = len(os.listdir(folder))
    print(f"{cls}: {count} gambar")

print("VALIDATION DATA")
for cls in classes:
    folder = os.path.join(val_path, cls)
    count = len(os.listdir(folder))
    print(f"{cls}: {count} gambar")

"""eda"""

import matplotlib.pyplot as plt
import numpy as np # Import numpy

labels = ["Normal", "COVID", "Tuberculosis"]
counts = [
    np.sum(y == 0),
    np.sum(y == 1),
    np.sum(y == 2)
]

plt.figure()
plt.bar(labels, counts)
plt.title("Distribusi Data per Kelas")
plt.xlabel("Kelas")
plt.ylabel("Jumlah")
plt.show()

"""HOG"""

X = []
y = []

label_map = {
    "Normal": 0,
    "Corona Virus Disease": 1,
    "Tuberculosis": 2
}

folders = [
    os.path.join(dataset_path,"train"),
    os.path.join(dataset_path,"val")
]

for folder_root in folders:

    for class_name,label in label_map.items():

        folder = os.path.join(
            folder_root,
            class_name
        )

        images = os.listdir(folder)

        for img_name in tqdm(images):

            img_path = os.path.join(
                folder,
                img_name
            )

            img = cv2.imread(
                img_path,
                cv2.IMREAD_GRAYSCALE
            )

            img = cv2.resize(
                img,
                (128,128)
            )

            features = hog(
                img,
                orientations=9,
                pixels_per_cell=(8,8),
                cells_per_block=(2,2),
                block_norm='L2-Hys'
            )

            X.append(features)
            y.append(label)

X = np.array(X)
y = np.array(y)

print(X.shape)
print(y.shape)

import cv2
from skimage.feature import hog
import matplotlib.pyplot as plt


img_path = sample_image_paths[0]

original_img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

img = cv2.resize(original_img, (128, 128))

features, hog_image = hog(
    img,
    orientations=9,
    pixels_per_cell=(8, 8),
    cells_per_block=(2, 2),
    block_norm='L2-Hys',
    visualize=True
)

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(img, cmap='gray')
plt.title("Sebelum HOG ")
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(hog_image, cmap='gray')
plt.title("Sesudah HOG")
plt.axis('off')

plt.show()

"""pca"""

pca = PCA(
    n_components=100,
    random_state=42
)

X_pca = pca.fit_transform(X)

print(X_pca.shape)

import numpy as np

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.hist(X[0].flatten(), bins=50)
plt.title("Distribusi Pixel (Sebelum HOG)")

plt.subplot(1,2,2)
plt.hist(features, bins=50)
plt.title("Distribusi Fitur (Sesudah HOG)")

plt.show()

"""scalling"""

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_pca)

"""split data"""

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""MLP"""

mlp = MLPClassifier(
    hidden_layer_sizes=(128,64),
    activation='relu',
    solver='adam',
    max_iter=300,
    random_state=42,
    verbose=True
)

mlp.fit(
    X_train,
    y_train
)

"""evaluasi"""

pred = mlp.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))
report = classification_report(y_test, pred, output_dict=True)

precision_normal = report['0']['precision']
precision_covid = report['1']['precision']
precision_tb = report['2']['precision']
accuracy = report['accuracy']

"""simpan model"""

joblib.dump(
    mlp,
    "model_xray.pkl"
)

joblib.dump(
    scaler,
    "scaler_xray.pkl"
)

joblib.dump(
    pca,
    "pca_xray.pkl"
)

from google.colab import files

files.download("model_xray.pkl")
files.download("scaler_xray.pkl")
files.download("pca_xray.pkl")

def is_likely_xray(img):

    if len(img.shape) == 3:
        img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    h, w = img.shape

    if h < 100 or w < 100:
        return False

    std = np.std(img)

    if std < 20:
        return False

    bright_ratio = np.sum(img > 240) / img.size

    if bright_ratio > 0.35:
        return False

    return True

"""streamlit"""

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import cv2
# import joblib
# import numpy as np
# import streamlit as st
# 
# from PIL import Image
# from skimage.feature import hog
# 
# model = joblib.load("model_xray.pkl")
# scaler = joblib.load("scaler_xray.pkl")
# pca = joblib.load("pca_xray.pkl")
# 
# def is_likely_xray(img):
# 
#     if len(img.shape) == 3:
#         img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
# 
#     h, w = img.shape
# 
#     if h < 100 or w < 100:
#         return False
# 
#     std = np.std(img)
# 
#     if std < 20:
#         return False
# 
#     bright_ratio = np.sum(img > 240) / img.size
# 
#     if bright_ratio > 0.35:
#         return False
# 
#     return True
# 
# st.set_page_config(
#     page_title="Deteksi Penyakit Paru",
#     layout="centered"
# )
# 
# st.title("Deteksi Penyakit Paru")
# 
# st.write("""
# Upload citra X-Ray dada untuk klasifikasi:
# 
# - Normal
# - COVID-19
# - Tuberculosis
# """)
# 
# uploaded_file = st.file_uploader(
#     "Pilih gambar X-Ray",
#     type=["jpg", "jpeg", "png"]
# )
# 
# if uploaded_file is not None:
# 
#     image = Image.open(uploaded_file)
# 
#     st.image(
#         image,
#         caption="Gambar yang diupload",
#         use_container_width=True
#     )
# 
#     img = np.array(image)
# 
#     if not is_likely_xray(img):
# 
#         st.error(
#             "Gambar tidak dikenali sebagai citra X-Ray paru-paru.\n\n"
#             "Silakan upload gambar X-Ray dada yang valid."
#         )
# 
#         st.stop()
# 
#     if len(img.shape) == 3:
# 
#         img = cv2.cvtColor(
#             img,
#             cv2.COLOR_RGB2GRAY
#         )
# 
#     img = cv2.resize(
#         img,
#         (128, 128)
#     )
# 
#     img = img.astype(np.float32) / 255.0
# 
#     feature = hog(
#         img,
#         orientations=9,
#         pixels_per_cell=(8, 8),
#         cells_per_block=(2, 2),
#         block_norm='L2-Hys'
#     )
# 
#     feature = feature.reshape(1, -1)
# 
#     feature = pca.transform(feature)
# 
#     feature = scaler.transform(feature)
# 
#     proba = model.predict_proba(feature)[0]
# 
#     confidence = np.max(proba)
# 
#     pred = np.argmax(proba)
# 
#     labels = {
#         0: "NORMAL",
#         1: "COVID-19",
#         2: "TUBERCULOSIS"
#     }
# 
#     if confidence < 0.60:
# 
#         st.warning(
#             " Tingkat keyakinan model rendah.\n\n"
#             "Pastikan gambar yang diunggah merupakan citra X-Ray paru-paru yang jelas."
#         )
# 
#     st.success(
#         f"Hasil Prediksi: {labels[pred]}"
#     )
# 
#     st.write(
#         f"Confidence: {confidence:.2%}"
#     )
# 
#     st.subheader("Probabilitas Kelas")
# 
#     st.write({
#         "NORMAL": f"{proba[0]*100:.2f}%",
#         "COVID-19": f"{proba[1]*100:.2f}%",
#         "TUBERCULOSIS": f"{proba[2]*100:.2f}%"
#     })
# 
#     st.bar_chart(
#         {
#             "Probabilitas": [
#                 float(proba[0]),
#                 float(proba[1]),
#                 float(proba[2])
#             ]
#         }
#     )

from pyngrok import ngrok

ngrok.set_auth_token("3E1d65tC0hjDUEyyUjDnTV26xSf_xPnrSvKoEKsfVYWF83i2")

from pyngrok import conf
conf.get_default().auth_token = "3E1d65tC0hjDUEyyUjDnTV26xSf_xPnrSvKoEKsfVYWF83i2"

from pyngrok import ngrok
public_url = ngrok.connect(8501)
print("URL Streamlit:", public_url)

!streamlit run app.py --server.port 8501 &